name: Workflow for Codecov
on: [push, pull_request]
jobs:
  upload:
    steps:
      name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      token: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
